#pragma once

enum class ActionType {
    OPEN_CREATION_POPUP,
    HIDE_CREATION_POPUP,
    CREATE_SESSION,
    OPEN_ALBUM,
    OPEN_FOLDER,
    CLOSE_SESSION,
    OPEN_IMAGE_POPUP,
    HIDE_IMAGE_POPUP
};
