#pragma once

enum class ActionType {
    OPEN_CREATION_POPUP,
    HIDE_CREATION_POPUP,
    OPEN_CONNECT_POPUP,
    HIDE_CONNECT_POPUP,
    CREATE_SESSION,
    OPEN_ALBUM,
    OPEN_FOLDER,
    CLOSE_SESSION,
    OPEN_IMAGE_POPUP,
    HIDE_IMAGE_POPUP,
    CONNECT_TO_ALBUM,
    SEND_IMAGES,
    SEND_MESSAGE,
    START_SERVER,
    CLIENT_CONNECTED,
};
